#!/bin/bash

if [ -z "${PREFIX}" ]; then
    echo "\`PREFIX\` was not specified." >&2
    exit 1
fi

libs="Libs: -L\${libdir} -linesi"
if [ -n "${AR}" ]; then
    libs+=$'\n'"Libs.private: -static"
fi

cat << EOF
prefix=$PREFIX
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: inesi
Description: INES File Parser Library
Version: 0.0
$libs
Cflags: -I\${includedir}
EOF