name: make CI
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
env:
  CC: gcc
  AR: ar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: make
    - name: Check Files Created
      uses: andstor/file-existence-action@v3
      with:
        files: "libinesi.so libinesi.a inesi inesi_static"