name: build test
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
env:
  CC: gcc
  AR: ar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: make
    # - name: Check Files Created
    #   uses: andstor/file-existence-action@v3
    #   with:
    #     files: "./libinesi.so ./libinesi.a ./inesi ./inesi_static"
    #     fail: true
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make
        run: make static
    # - name: Check Files Created
    #   uses: andstor/file-existence-action@v3
    #   with:
    #     files: "./libinesi.a ./inesi_static"
    #     fail: true